/*
# Customer PIN Authentication System

## Summary
Replaces the OTP-based customer authentication with a secure PIN-based system.
Customers log in with their registered phone number and a personal 4-digit PIN.
First-time activation requires a temporary activation PIN generated by an admin.

## 1. New Tables

### client_pins
Stores the hashed PIN for each customer. Never stores plain-text PIN.
- `client_id` (uuid, FK clients, unique) — one PIN per customer
- `pin_hash` (text, not null) — PBKDF2 hash of the 4-digit PIN
- `pin_salt` (text, not null) — random salt used for hashing
- `pin_iterations` (integer, default 100000) — PBKDF2 iteration count
- `failed_attempts` (integer, default 0) — failed login attempt counter
- `locked_until` (timestamptz, nullable) — lockout expiry timestamp
- `last_login_at` (timestamptz, nullable) — last successful login
- `pin_created_at` (timestamptz, default now())
- `pin_updated_at` (timestamptz, default now())

### client_activation_codes
Single-use activation codes for first-time PIN setup.
- `client_id` (uuid, FK clients) — the customer to activate
- `code_hash` (text, not null) — hash of the activation code
- `code_salt` (text, not null) — salt for the activation code hash
- `expires_at` (timestamptz, not null) — expiry timestamp (24h)
- `used_at` (timestamptz, nullable) — when consumed (null = unused)
- `created_by` (text, nullable) — admin who generated it
- `created_at` (timestamptz, default now())

## 2. Modified Tables

### client_sessions
- Added `revoked` (boolean, default false) — supports session revocation on logout/PIN change

## 3. Security
- RLS enabled on both new tables.
- client_pins: deny-by-default. All reads/writes go through the edge function
  using the service role key (server-side only). No anon/authenticated policies
  are created — the table is invisible to the frontend.
- client_activation_codes: same deny-by-default approach.
- client_sessions: existing policies preserved. Added anon SELECT for session
  validation by the frontend.
*/

-- ===== client_pins =====
CREATE TABLE IF NOT EXISTS client_pins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL UNIQUE REFERENCES clients(id) ON DELETE CASCADE,
  pin_hash text NOT NULL,
  pin_salt text NOT NULL,
  pin_iterations integer NOT NULL DEFAULT 100000,
  failed_attempts integer NOT NULL DEFAULT 0,
  locked_until timestamptz,
  last_login_at timestamptz,
  pin_created_at timestamptz NOT NULL DEFAULT now(),
  pin_updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_client_pins_client ON client_pins(client_id);

ALTER TABLE client_pins ENABLE ROW LEVEL SECURITY;
-- No policies = deny-by-default. Only the service role (edge function) can access.

-- ===== client_activation_codes =====
CREATE TABLE IF NOT EXISTS client_activation_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  code_hash text NOT NULL,
  code_salt text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_client_activation_codes_client ON client_activation_codes(client_id);

ALTER TABLE client_activation_codes ENABLE ROW LEVEL SECURITY;
-- No policies = deny-by-default. Only the service role (edge function) can access.

-- ===== client_sessions: add revoked column =====
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'client_sessions' AND column_name = 'revoked'
  ) THEN
    ALTER TABLE client_sessions ADD COLUMN revoked boolean NOT NULL DEFAULT false;
  END IF;
END $$;

-- Allow anon to validate sessions (SELECT only, by token)
DROP POLICY IF EXISTS "anon_select_client_sessions" ON client_sessions;
CREATE POLICY "anon_select_client_sessions" ON client_sessions
  FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_client_sessions" ON client_sessions;
CREATE POLICY "anon_insert_client_sessions" ON client_sessions
  FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_client_sessions" ON client_sessions;
CREATE POLICY "anon_update_client_sessions" ON client_sessions
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_client_sessions" ON client_sessions;
CREATE POLICY "anon_delete_client_sessions" ON client_sessions
  FOR DELETE TO anon, authenticated USING (true);
